dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - psql -U postgres -c "create database decide owner decide"
language: python
python:
  - "3.6"
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - ./manage.py test --keepdb
branches:
  only:
  - master
deploy:
  provider: heroku
  app: examenfraromgon2
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: master
